### ISSUE TITLE
No result output

### ISSUE THREAD

**Issue by zer0nka** [JaidedAI/EasyOCR#78]
Hello.
I installed pytorch by this command "pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html" 
and used basic code for test OCR

import easyocr
reader = easyocr.Reader(['en'])
reader.readtext('example.jpg') 

example.jpg was token from "https://github.com/JaidedAI/EasyOCR/raw/master/examples/example.png" and converted to jpg

I have no result output. I use windows 10 and pytorch in CPU only mode. I tried both stable and development releases.

stdout:
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading recognition model, please wait
Download complete

**Comment by rkcosmos** [comment]
Can you try with other random images with clear text? preferably high resolution

**Comment by FlorentijnD** [comment]
Could you share the converted jpg image?

**Comment by rkcosmos** [comment]
I just uploaded additional test image to examples folder.

**Comment by bit-scientist** [comment]
@rkcosmos , I have the same issue here. I am on Win 10, with python 3.9.12, CUDA 11.3. I created a cond `env`, installed cudatoolkit=11.3 using pip in official pytorch page, verified the installation. `import easyocr` worked, but `reader = easyocr.Reader(['ko','en'])` threw some warnings:
`C:\Users\user\anaconda3\envs\easyocr\lib\site-packages\torchvision\models\_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and will be removed in 0.15. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
C:\Users\user\anaconda3\envs\easyocr\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
C:\Users\user\anaconda3\envs\easyocr\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)`

Then, `result = reader.readtext('S:\\local\\EasyOCR\\examples\\id_custom\\20220713_112246.jpg')` resulted `Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127` error. 

I found a "solution" to it which is:
```
import ctypes
hllDll = ctypes.WinDLL("C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cublas64_11.dll")
```
cublas error disappeared, but the doe isn't returning anything, no error, no list of outputs, just a blank.

What could be the problem here? Thank you.
