### ISSUE TITLE
deform_conv_cuda not found in deform_conv

### ISSUE THREAD

**Issue by Mahmuod1** [JaidedAI/EasyOCR#832]
![Screenshot from 2022-08-25 15-01-56](https://user-images.githubusercontent.com/79579124/186672223-d3013e49-5b7c-4faa-89cd-f45709a8d9be.png)

**Comment by purplesword** [comment]
I met same issue trying initializing `reader = easyocr.Reader(["en", "de"], detect_network="dbnet18")` 


```
File ~/.virtualenvs/py3106/lib/python3.10/site-packages/easyocr/DBNet/assets/ops/dcn/functions/deform_conv.py:5, in <module>
      2 from torch.autograd import Function
      3 from torch.nn.modules.utils import _pair
----> 5 from .. import deform_conv_cuda
      8 class DeformConvFunction(Function):
     10     @staticmethod
     11     def forward(ctx,
     12                 input,
   (...)
     19                 deformable_groups=1,
     20                 im2col_step=64):

ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'easyocr.DBNet.assets.ops.dcn' (most likely due to a circular import) 
```

**Comment by purplesword** [comment]
I've tried various combinations with 
* python 3.7/3.8/3.9/3.10, 
* torch 1.7/1.9/1.10/1.12, 
* cuda 10.1/11.3/11.6/11.7, 
* ubuntu 20.04/22.04, 
* via `pip instal easyocr`/with `python compile_dbnet_dcn.py`. 

Unfortunately all of them failed at this step. 

Anyone managed to get it running? Could you share you env setting and lib versions?

**Comment by timchann124** [comment]
Encountered the same issue

**Comment by ogencoglu** [comment]
Same error here.

**Comment by dilerbatu** [comment]
Same issue.

**Comment by rkcosmos** [comment]
hi all, can you try the last version (1.6.2)?

**Comment by Mahmuod1** [comment]
thanx it is work

**Comment by nguyenvulong** [comment]
I solved it with `conda install cuda-nvcc`
